// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CaroMatch struct {
	ID                  pgtype.UUID        `json:"id"`
	XPlayerID           pgtype.UUID        `json:"xPlayerId"`
	XPlayerRatingBefore int32              `json:"xPlayerRatingBefore"`
	XPlayerRatingAfter  int32              `json:"xPlayerRatingAfter"`
	OPlayerID           pgtype.UUID        `json:"oPlayerId"`
	OPlayerRatingBefore int32              `json:"oPlayerRatingBefore"`
	OPlayerRatingAfter  int32              `json:"oPlayerRatingAfter"`
	WinnerID            pgtype.UUID        `json:"winnerId"`
	FinalBoard          []byte             `json:"finalBoard"`
	Moves               []byte             `json:"moves"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Role           string             `json:"role"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalizedName"`
	AvtCode        string             `json:"avtCode"`
	Email          pgtype.Text        `json:"email"`
	CaroRating     int32              `json:"caroRating"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}
