// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, name, avt_code, email, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Name,
		&i.AvtCode,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, role, name, avt_code, email, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Name,
		&i.AvtCode,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    id,
    role,
    name,
    avt_code,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertUserParams struct {
	ID      pgtype.UUID `json:"id"`
	Role    UserRole    `json:"role"`
	Name    string      `json:"name"`
	AvtCode UserAvtCode `json:"avtCode"`
	Email   pgtype.Text `json:"email"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Role,
		arg.Name,
		arg.AvtCode,
		arg.Email,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    role = $2,
    name = $3,
    avt_code = $4,
    email = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID      pgtype.UUID `json:"id"`
	Role    UserRole    `json:"role"`
	Name    string      `json:"name"`
	AvtCode UserAvtCode `json:"avtCode"`
	Email   pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Role,
		arg.Name,
		arg.AvtCode,
		arg.Email,
	)
	return err
}
